name: Main Build
on:
  pull_request:
    branches:
      - main

jobs:
  adopt-ruff:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with: 
          python-version: 3.x
  
      - name: Install ruff 
        run: pip install ruff

      - name: Run the adopt-ruff action
        uses: chartboost/ruff-action@v1

  pytests:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with: 
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run tests
        run: |
          pytest src
        
         
