name: Docs build and upload

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Sphinx Build
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "src/docs/"

      - name: Github Pages upload
        uses: actions/upload-artifact@v4
        with:
          name: DocumentationHTML
          path: "src/docs/_build/html/"
