name: Docs build and upload

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Deps
        run: |
          pip install sphinx
          pip install -r src/docs/requirements.txt

      - name: Sphinx Build
        run: |
          cd 'src/docs/'
          make html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages Artifact
        #        uses: actions/deploy-pages@v4
        uses: actions/upload-pages-artifact@v3
        with:
          path: "src/docs/_build/html"

      - name: Deplot GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
